steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "build"
      - "-f"
      - "apps/congressional-ingest/Dockerfile"
      - "-t"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/trader-repo/congressional-ingest:${SHORT_SHA}"
      - "-t"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/trader-repo/congressional-ingest:latest"
images:
  - "us-east4-docker.pkg.dev/${PROJECT_ID}/trader-repo/congressional-ingest:${SHORT_SHA}"
  - "us-east4-docker.pkg.dev/${PROJECT_ID}/trader-repo/congressional-ingest:latest"
